### ISSUE TITLE
Error: Browser does not exist

### ISSUE THREAD

**Issue by lmachens** [tsuyoshiwada/storybook-chrome-screenshot#90]
Hi, I installed `storybook-chrome-screenshot` 1.3.0 and face this error when running `npm run screenshot` on Windows 10:
```
UnhandledPromiseRejectionWarning: Error: Browser does not exist
    at Browser.<anonymous> (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:70:27)
    at step (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:32:23)
    at Object.next (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:13:53)
    at C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:3:12)
    at Browser.close (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\Browser.js:67:16)
    at C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\App.js:217:100
    at Array.map (<anonymous>)
    at App.<anonymous> (C:\app\node_modules\storybook-chrome-screenshot\lib\core\app\App.js:217:72)
```

There are no warnings/errors when installing puppeteer.

Thanks!

**Comment by Iar0** [comment]
had the same on windows 10, but I had to set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD to true because of company restricted access. How can I run it on chrome/chromium? The first is installed, for the second I have the exe

**Comment by roalonso** [comment]
Pass the browser you want to use on storybook-chrome-screenshot as Puppeteer configuration, for example, if you have Chrome:
```
> storybook-chrome-screenshot --puppeteer-launch-config '{"args": ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"], "executablePath": "chrome.exe"}'
```

**Comment by adirn15** [comment]
@lmachens did you manage to resolve the issue?

**Comment by lmachens** [comment]
@adirn15 no sry

**Comment by MasterMotoi** [comment]
Hi, I'm hitting the exact same issue on windows 10 when trying to execute storybook-chrome-screenshot. Is there any solution for this ?
